[package]
name = "day_17"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = "0.1.0"
itertools = "0.12.1"
utility = "0.0.0"
